In [1]:
import numpy as np
import matplotlib.pyplot as plt

Exercise 6.1

In [41]:
class Exercise6i():
    def __init__(self):
        
        self.numpoints = 201
        self.xmin = -10
        self.xmax = 10
        self.tmax = 10
        
        self.t = 0
        self.dx = .1
        self.dt = .1
        
        self.v = 1
        
        self.x = np.linspace(self.xmin, self.xmax, self.numpoints)
        self.u = np.where( (self.x >= -2) & (self.x <= 0), np.sin(np.pi * self.x), 0) #t = 0
        
        self.alpha = self.v * self.dt / (2 * self.dx)
        
    def step(self):
    
        # Enforce boundary conditions
        self.u[0] = 0
        self.u[-1] = 0 
        
        self.u[1:-1] = self.u[1:-1] - self.alpha * (self.u[2:] - self.u[0:-2])
        
        self.t += self.dt
        
        if self.t >= self.tmax:
            print('Done')
            return True
        

In [43]:
a = Exercise6i()

In [44]:
a.step()

In [45]:
a.u


array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [21]:
y

array([-10.,  -6.,  -2.,   2.,   6.,  10.])

In [26]:
b = np.array([0,1,2,3,4,5,0])

In [32]:
b[1:-1]

array([1, 2, 3, 4, 5])

In [33]:
b[0:-2]

array([0, 1, 2, 3, 4])

In [34]:
b[2:]

array([2, 3, 4, 5, 0])

In [35]:
c = b[1:-1] - (b[2:] - b[0:-2])

In [36]:
c

array([-1,  0,  1,  2,  9])