In [1]:
import numpy as np


In [7]:
a = np.linspace(-2, 2, 10)

In [8]:
a[a > 0]

array([0.22222222, 0.66666667, 1.11111111, 1.55555556, 2.        ])

In [9]:
b = np.linspace(0,5,10)

In [10]:
np.where(a > 0, b, 0)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
b

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])